### ISSUE TITLE
Double panel in UI

### ISSUE THREAD

**Issue by davisford** [lloiser/go-debug#10]
Not sure where this bug lies, go-debug, atom.io or what.

![screen shot 2016-04-07 at 8 43 50 pm](https://cloud.githubusercontent.com/assets/186677/14371058/9ac06360-fd01-11e5-8f7a-031735ead3e3.png)

**Comment by lloiser** [comment]
I'm working on it! Happens if you deactivate and activate go-debug in settings.

**Comment by davisford** [comment]
Cool.  Having some other issues too, but I think they are more `delve` related.  Well, sometimes when I try to tab between Test / Debug I can't get it to display the toolbar at the top `(play | next | stepinto | restart | stop)`.   What determines when that toolbar will show up?

Tests seem to work ok, and I can debug tests, but debugging a heavyweight server process is giving me some headache.  Most of the time I cannot get that toolbar to show up.  Sometimes it works and then I click play, and I am able to step (kinda).  Sometimes it seems `delve` goes off into the weeds, and it just won't respond to the commands anymore.  The output console just says things like:

![screen shot 2016-04-08 at 10 50 50 am](https://cloud.githubusercontent.com/assets/186677/14387515/c9b092f0-fd77-11e5-9817-8aee09e87782.png)

The last one is where I hit `stop`, which does seem to work.  Just super buggy right now, but that may not be the plugin's fault.  I'm trying to use `delve` now at the cmd-line to see if I can get that working and provide more effective feedback for you with the plugin.
