### ISSUE TITLE
The debugger is not ready ... 

### ISSUE THREAD

**Issue by Nate94305** [lloiser/go-debug#100]
Hi!

I am having a trouble of using go-debug in Atom with delve. Delve itself works fine on command line window or terminal. However, I have never got the debug menus as in the movie on https://github.com/lloiser/go-debug. 

Here is my environment: 
- OS: macOS Sierra 10.12.4.
- Atom: 1.17.0
- go-debug: 1.4.0
- delve: Version: 1.0.0-rc.1

Installation process:
- home brew was used to install and upgrade delve
- Atom package installer was used to install an upgrade go-debug

Symptom in Debug on go-plus window at the bottom: "The debugger is not ready ..."
--> Please take a look at the attached snapshot.

Thanks

Nathan

**Comment by Nate94305** [comment]
<img width="1250" alt="2017-05-24 4 23 13" src="https://cloud.githubusercontent.com/assets/6182785/26391681/a452ea06-409e-11e7-9422-b01988746422.png">

**Comment by lloiser** [comment]
So what did you do to fix this?

**Comment by Nate94305** [comment]
I changed /User/sanghwankim/.atom/config.cson by adding as below. Still not working
<img width="707" alt="2017-05-25 12 49 43" src="https://cloud.githubusercontent.com/assets/6182785/26435619/80197aa8-414b-11e7-8a12-ca79cac8ce35.png">

So, I added debug_config file under /.atom directory with the following contents: but still not working
{
  "name": "Debug cmd",
  "mode": "debug","test"
}


Any advise?

**Comment by lloiser** [comment]
It typically should not be necessary to set `dlvPath`. go-debug checks various directories like `$GOPATH/bin` and `$PATH`. You have installed it with brew so it should be in your `$PATH` already. 
Nevertheless if you want to set `dlvPath` then this has to be the absolute path to the `dlv` executable. So in your case this may look like `/usr/local/bin/dlv` (if `dlv` is inside `/usr/local/bin`)

The `configurationFile` setting is meant to be "relative to your current project". If the path is relative it tries to find the file relative to your opened folder in atom. This gives you the advantage to prepare the configuration file for each project. On the other hand you can also set a absolute path that might be used for all projects.

The configuration you posted at the end is not a valid JSON file. The configuration file should look like
```js
{
  "configurations": [
    {
      "name": "Verbose Test",
      "mode": "test",
      "args": ["-v"]
    }
  ]
}
```

**Comment by Nate94305** [comment]
Thanks.

After reading your comment,  I changed the debug_config file first, then I changed the path to configurationFile in config.cson to the absolute path. Still not working.
I also tried the relative path with copied debug_config within the project directory. Still not working.

Any suggestion?

**Comment by lloiser** [comment]
And what about the `dlvPath` setting? Either remove it at all or insert the absolute path to the `dlv` executable. As mentioned above this might be `/usr/local/bin/dlv`
