### ISSUE TITLE
missing modules macOS sierra Atom 1.17.2

### ISSUE THREAD

**Issue by jare19** [lloiser/go-debug#101]
Output from `atom --debug`
```
Failed to require the main module of 'go-debug' because it requires one or more incompatible native modules (binding, binding, binding, binding, binding).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

go-debug 1.4.2
```
binding@unknown – Cannot find module '/REDACTED/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/REDACTED/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/REDACTED/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/REDACTED/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '/REDACTED/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
```

I have tried to apm rebuild/update many times but resulting in the same error.

**Comment by lloiser** [comment]
What's the output of `atom --version`, `apm --version` and `node --version`?
Have you recently upgraded atom and/or node?
Do you remember how you installed `go-debug` in the first place?

A few solutions:
* remove the `go-debug` folder and use `apm install go-debug`. 
* remove the `go-debug` folder and install `go-debug` via the atom `Install` settings tab. 
* run `apm rebuild` inside `/REDACTED/.atom/packages/go-debug`
* afaik atom shows a "red bug" in the bottom right corner if this happens. Clicking it opens a tab that shows the packages that are "incompatible". There should be a "rebuild" button or something like this next to the package. It might fix it too.

**Comment by jare19** [comment]
thanks, removing the folder and then installing via `sudo apm install go-debug` and then rebuilding worked for me
