### ISSUE TITLE
Can't  reach a breakpoint, stuck in another function

### ISSUE THREAD

**Issue by krasi-georgiev** [lloiser/go-debug#102]
https://gist.github.com/krasi-georgiev/516155ca4808606e77037149f9995869

it never reaches a breakpoint at `fmt.Println(bufStream)`

clicking the Resume button does nothing

it gets stuck in portaudio.go at 

```
func (s *Stream) Start() error {
	return newError(C.Pa_StartStream(s.paStream))
}
```

Delve Version: 1.0.0-rc.1
go1.8 darwin/amd64
Atom 1.17.2
go-debug 1.4.3

Here is a short video
https://screencast.com/t/gzxr1utP2b0t

**Comment by lloiser** [comment]
Thanks for providing the code. Unfortunately I'm not able to get this code running...

Please try to run your code in the terminal with delve using `dlv debug` and check if the problem occurs there too. If so please open a bug at https://github.com/derekparker/delve

**Comment by krasi-georgiev** [comment]
ah yes you need to install portaudio
`brew install portaudio`

can you try to reproduce and if not I will learn how to run dlv in the console.

**Comment by lloiser** [comment]
I did that already but as I said I get some errors (at least on ubuntu, I have no mac at hand).

Just `cd` to your `main.go` file and run `dlv debug`. From there on you can set a breakpoint using `b main.go:24` (as in your video) and continue with `c`.

**Comment by krasi-georgiev** [comment]
You were right the issue is with the delve package
