### ISSUE TITLE
How can i set the launch args for main function？

### ISSUE THREAD

**Issue by miludedeng** [lloiser/go-debug#104]
I hava a project read paramters by flag. I'm using the go-debug plugin for Atom，how can i set the paramter for developer env。

**Comment by lloiser** [comment]
The README provides quite some details how to add [**configurations**](https://github.com/lloiser/go-debug#configuration) to go-debug:

You basically have to create a file, most likely somewhere inside your project folder. The relative path to this file has to be added to the `Configuration File` setting of go-debug.

The file contains the following JSON:

```json
{
  "configurations": [
    {
      "name": "Debug cmd",
      "mode": "debug",
      "cwd": "${workspaceRoot}/cmd",
      "args": ["--connection=sql"],
      "env": {
        "USER": "ROOT",
        "PW": "SECRET!"
      }
    }
  ]
}
```

`args` is an array of strings that are passed to your program
`env` are enviroment variables
`cwd` is the folder that contains your `main` package

Now that everything is configured, you should see this config _Debug cmd_ in the select box in the debugger panel.

-----

And _please read the README_, if something is unclear, please reopen this issue.
