### ISSUE TITLE
Reading from debug text input

### ISSUE THREAD

**Issue by Gujie-Novade** [lloiser/go-debug#107]
Hi,
Is there anyway we can read data from the text input (see bottom of the screenshot)?
I tried:
`reader := bufio.NewReader(os.Stdin)
email, _ := reader.ReadString('\n')`
But I'm not getting anything...
Thanks for your help!
<img width="1017" alt="screenshot 2017-07-12 19 42 17" src="https://user-images.githubusercontent.com/14208739/28116120-3ae050a0-673a-11e7-8275-7602db3a65d1.png">

**Comment by lloiser** [comment]
delve does not support reading from stdin.
See https://github.com/lloiser/go-debug/issues/41 and https://github.com/derekparker/delve/issues/65
