### ISSUE TITLE
Error  on ATOM version 1.18.0 x64

### ISSUE THREAD

**Issue by sixpac009** [lloiser/go-debug#113]
Just tried to install go-debug and ATOM is giving an error message after the restart.  Is there a possible fix for this? 
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

go-debug 1.5.2

>binding@unknown – Cannot find module '\~/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '\~/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '\~/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '\~/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '\~/.atom/packages/go-debug/node_modules/fsevents/lib/binding'
binding@unknown – Cannot find module '\~/.atom/packages/go-debug/node_modules/fsevents/lib/binding'

**Comment by lloiser** [comment]
have a look at this issue: https://github.com/lloiser/go-debug/issues/110

**Comment by lloiser** [comment]
This should be fixed with the latest version 1.6.0
