### ISSUE TITLE
The debugger is not ready ...

### ISSUE THREAD

**Issue by dishmaev** [lloiser/go-debug#121]
Hi

I am having a trouble of using go-debug in Atom with delve.

go-debug version 1.5.2

OS: Debian 9
Linux IT-X1 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux
go version
go version go1.9.2 linux/amd64

OS: MacOS 10.13.2
Darwin HOME-NB.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

config.cson
"*":
  core:
    telemetryConsent: "no"
  "exception-reporting":
    userId: "da02bf84-98c0-4205-bb9b-29ec0a2c8670"
  "go-debug":
    configurationFile: [
      "/home/dmitry/debug_config"
    ]
    dlvPath: "/home/dmitry/go/bin"
  welcome:
    showOnStartup: false

$ dlv version
Delve Debugger
Version: 1.0.0-rc.2
Build: $Id: 5c7676404d10d52e16be57fea744a7312b831f0c

/home/dmitry/debug_config
{
  "configurations": [
    {
      "name": "Verbose Test",
      "mode": "test",
      "args": ["-v"]
    }
  ]
}

I read https://github.com/lloiser/go-debug/issues/100, this is a very similar problem

Where to find configuration files for built-in Debug and Test?
quote from README.md below
`go-debug` has two built-in configurations. Both work on the file/package that is currently open in atom.

* `Debug`: compile and debug the current package
* `Test`: compile and debug the tests of the current package

**Comment by Uplink03** [comment]
I'm getting this now after installing a go-debug update earlier. I was on Atom 1.21.1 when I installed the update that broke it. I'm on 1.23.1 now.

**Comment by Uplink03** [comment]
Well, in my case I "fixed" it like this: `rm ~/go/bin/dlv`

Then when I started Atom go-debug complained that dlv wasn't there and offered to `go get -u github.com/derekparker/delve/cmd/dlv`

The strange part here is that I ran that `go get` exactly like that myself earlier, when I noticed my debug panel wasn't showing up. I don't know why doing the above would fix it.

**Comment by Uplink03** [comment]
That fix doesn't last. Restart Atom and I get back to square one. Start Atom with dlv missing, tell go-debug to fetch it, and I have a debugger until I quit Atom.

This should be a hint of what's going wrong for somebody familiar with the source code.

**Comment by ryeden** [comment]
Same here: remove dlv.exe (on Windows), disable/reenable the plugin and it starts working. But after restarting Atom it goes back to square one.

**Comment by lloiser** [comment]
Should be fixed with 1.5.3. Please update go-debug.

**Comment by dishmaev** [comment]
now it work
thank you

**Comment by ryeden** [comment]
Nope, it didn't help me at all. I've tried to reinstall (and then uninstall & install) go-debug and go-plus - all with same result.

**Comment by EdwinKing001** [comment]
I am facing the same problem now, go-debug ver:1.6.2, ATOM1.35.1 x64, go plus 6.1.0
