### ISSUE TITLE
Any way to pass args to debug binary?

### ISSUE THREAD

**Issue by davisford** [lloiser/go-debug#13]
Seems [delve supports this](https://github.com/derekparker/delve/issues/440)?

**Comment by lloiser** [comment]
see https://github.com/lloiser/go-debug/issues/7#issuecomment-208521292

**Comment by davisford** [comment]
The `exec` command is for debugging a pre-compiled binary, but the `debug` command clearly accepts additional params which it will pass directly to the program being debugged.  

I'm just looking for a way to pass from the plugin to the `debug` command after the `--`, i.e. 

* `delve debug myapp -- -foo=bar`

I wouldn't worry too much about the perfect config UI.  I'd be happy with just a simple text box that would just pass the string `-foo=bar` above into the executable launching of the `delve` debug session after the `--`

**Comment by lloiser** [comment]
see newest version
