### ISSUE TITLE
i meet the following error 

### ISSUE THREAD

**Issue by chenxuaning** [lloiser/go-debug#140]
go version 1.10.1
dev tool: atom

![image](https://user-images.githubusercontent.com/34224979/41239058-1f68dd5a-6dca-11e8-9f73-e192821e737b.png)

**Comment by lloiser** [comment]
This seems to be an error in delve itself. Please update your `dlv`binary using `go get -u github.com/derekparker/delve/cmd/dlv`. If the error persists please open an bug over at delve: https://github.com/derekparker/delve/issues
