### ISSUE TITLE
The debugger doesn't show pointer values

### ISSUE THREAD

**Issue by johnsonz** [lloiser/go-debug#149]
Any ideal to show pointer values?

**Comment by lloiser** [comment]
Works for me.
![screenshot](https://user-images.githubusercontent.com/3003233/53159934-29f1fe80-35c7-11e9-904b-a6225e5e5320.png)

Can you provide some code?
Is the value you try to inspect nested in other structs/arrays/maps?

**Comment by johnsonz** [comment]
Sorry I didn't make myself clear. 
Any way to check the value of `t` in `Variables` like fmt.Println()?

![capture](https://user-images.githubusercontent.com/2533629/53216027-25dce400-368e-11e9-8482-ffad816c24ac.PNG)
![capture1](https://user-images.githubusercontent.com/2533629/53216028-2aa19800-368e-11e9-9567-8a71050b45de.PNG)
![capture2](https://user-images.githubusercontent.com/2533629/53216031-2c6b5b80-368e-11e9-9395-9f60b1e028dc.PNG)

**Comment by lloiser** [comment]
Not really, even delve does not support this kind "pretty printing".

**Comment by johnsonz** [comment]
Thx buddy.
