### ISSUE TITLE
Use go-get to install delve

### ISSUE THREAD

**Issue by mishak87** [lloiser/go-debug#15]
https://atom.io/packages/go-get

**Comment by lloiser** [comment]
It is not `go get` able yet, you still need `make` for building and on OSX you also need a certificate.

Although there is an issue to improve this https://github.com/derekparker/delve/issues/494

**Comment by mishak87** [comment]
Sorry I have misread [linux](https://github.com/derekparker/delve/blob/master/Documentation/installation/linux/install.md) doc and assumed it has been fixed :disappointed:. I'll reopen if situation changes.

**Comment by joefitzgerald** [comment]
We could use go-get on Linux? And then download something precompiled on Windows and Darwin...
