### ISSUE TITLE
with atom 1.34.0 lauch debugger from pull down menu does not work

### ISSUE THREAD

**Issue by apmattil** [lloiser/go-debug#150]
I'm not sure if this issue should be at atom or go-plus or this plugin but,
lauch debugger from pull down menu does not work.
F5 works, but this is not clear from documentation.

**Comment by lloiser** [comment]
If you mean the `Debugger` menu entry next to the `Help` - this comes from `atom-ide-ui` and is not related to `go-debug`.

A little bit of info:
atom-ide-ui (which is a bundle of several utility UIs for atom) provides a debugger UI. Apparently, it did not provide the necessary features I needed for go-debug. Unfortunately, atom-ide-ui has been archived earlier this year, so I will definitely not use this feature in the future.
You can disable the atom-ide-ui debugger (and the menu entry) in its settings -> set `Enabled Features - Enable Debugger` to `Never enabled`.

**Comment by apmattil** [comment]
Hi
Thank you for responding, I found the disable setting.

You package work well.. really needed feature.
I would still clarify the documentation how to start it.

What I was left missing was dlv cmd prompt, I would like to just print a
variable with full lenght.. e.g string.

Br, Ari Mattila

**Comment by lloiser** [comment]
I'm always open to merge requests to improve the documentation or the plugin itself :)

**Comment by apmattil** [comment]
I have never made a pull request.. now is good time to try.. I'll do it ;)
