### ISSUE TITLE
Issues trying to use Go-Debug

### ISSUE THREAD

**Issue by carlca** [lloiser/go-debug#159]
- macOS 10.14.6
- go version go1.16 darwin/amd64
- go env
- GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/Users/carlca/Code/go/bin"
GOCACHE="/Users/carlca/Library/Caches/go-build"
GOENV="/Users/carlca/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/carlca/Code/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/carlca/Code/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/carlca/code/go/src/github.com/carlca/gowig/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1d/1rqcnlq51zd4j_vqhp1kv3540000gp/T/go-build3227935998=/tmp/go-build -gno-record-gcc-switches -fno-common"  
- Atom v 1.57.0 x64

I have downloaded and installed `dlv` and have installed Go-Debug . I have verified that `dlv` is installed by running it in VS-Code. 

My configuration path is defined thus:
Configuration Path: /Users/carlca/.atom/debug.cson

My `dlv` path is defined thus:
/Users/carlca/code/go/bin/dlv

My `debug.cson` file contains...
```
{
  	"configurations": [
   		{
			"name": "Debug cmd",
    			"mode": "debug",
    			"cwd": "${workspaceRoot}/cmd",
    			"args": [
				" Diffusion.bwpreset"
    			]
		}
	]
}
```

If I load a `main.go` which I have successfully debugged in VSCode, in Atom, and hit Cmd F8, I get a popup error message saying that there is no debugger installed.

![Screenshot 2021-06-01 at 17 55 17](https://user-images.githubusercontent.com/260612/120362171-ad503d80-c302-11eb-844c-0c8ed6d7efd5.png)

The menu option to Launch is disabled. My only option available is to Cancel the operation.

In case you are wondering why I don't simply use VS-Code to debug, the problem is that VS-Code currently has no way of displaying Watch values in anything other than decimal. I have seen suggestions of a postfix solution: <var name>, h , but this doesn't work. And besides I'd rather keep everything in Atom.

I hope that's enough detail for you. If you could enlighten me on how to debug using Go-Debug with Atom, I would be very grateful 😉

**Comment by lloiser** [comment]
Hey, sorry for the late response. I have not used atom in like 5 years because I switched to VSCode.

It seems there is some other debugger extension installed that overwrites the keybindings that I added for go-debug. Maybe you can overwrite them with custom keybindings back to go-debug...
 
You have to click the _play_ button in the go-debug panel on the right which contains all the controls, callstack and variables. Also the output panel of the debugger is located in the go-plus panel (usually sits at the bottom) in the 🐞  tab.

**Comment by carlca** [comment]
Thanks for the response. In the end I moved away from Atom to telemetries-free VSCodium, which has the same features as VSCode, but somehow seems more snappy. Rather than use built in debugging, I have discovered https://github.com/aarzilli/gdlv which is a very nice front end for Delve, developed bay someone who has worked alongside Derek Parker.
