### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addBreakpoint' of null

### ISSUE THREAD

**Issue by parabatareek** [lloiser/go-debug#160]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.61.0-beta0 x64
**Electron**: 11.4.12
**OS**: "Manjaro Linux"
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'addBreakpoint' of null

```
At /home/gavrosh/.atom/packages/go-debug/lib/debugger.js:128

TypeError: Cannot read property 'addBreakpoint' of null
    at Debugger._addBreakpoint (/packages/go-debug/lib/debugger.js:128:26)
    at Debugger.addBreakpoint (/packages/go-debug/lib/debugger.js:118:17)
    at Debugger.toggleBreakpoint (/packages/go-debug/lib/debugger.js:174:19)
    at Editor.handleGutterClick (/packages/go-debug/lib/editor.js:109:15)
```

### Commands

```
     -2:21.1.0 golang:update-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 10x -1:44.1.0 go-debug:next (span.icon-arrow-right)
     -1:05.5.0 go-debug:restart (span.icon-sync)
     -0:53.5.0 go-debug:stop (button.btn.go-debug-btn-flat)
     -0:22.3.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-runner 2.7.1 
data-explorer 0.7.0 
go-debug 1.7.0 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
Hydrogen 2.16.3 
hydrogen-cell-separator 0.4.1 
markdown-cell-highlight 1.2.0 
```

**Comment by lloiser** [comment]
Thank you for opening this issue.
Have you read the news about atom? https://github.blog/2022-06-08-sunsetting-atom/
Sorry to say, but I won't invest any time fixing this issue.
I can recommend switching to vscode instead 🙂
