### ISSUE TITLE
Go Debug not working in Atom

### ISSUE THREAD

**Issue by mgarciapatz** [lloiser/go-debug#17]
Hi i have installed this plugin and the delve package at the same time for Atom however after pressing keys f5 or anything that was included in guides and usage. Nothing happens, no toggle panel or debugger output. Is there something that I should do first before trying it to Atom IDE? anyway I am using Ubuntu. Thanks.

**Comment by lloiser** [comment]
#16 #12 #8 ?

**Comment by mgarciapatz** [comment]
sorry for late reply i tried and study the 3 but still its not working. i tried npm install but doesnt work.

**Comment by lloiser** [comment]
The panel should be visible after installing it... maybe something went wrong. You can show/hide the panel using `ctrl-k ctrl-g` / `cmd-k cmd-g`.

Nothing changed?

Open the developer tools in atom (`alt-cmd-i / alt-ctrl-i`) and check the console. Do you see any logs there?

**Comment by mgarciapatz** [comment]
Hello there, sorry for late response, i am very new with this editor and
there's nothing happens when i use alt+ctrl+i however i manage to do this
one. see image thank you

**Comment by mgarciapatz** [comment]
i saw your new update and gets this error one after clicking update.
![Uploading godebugupdate.png…]()

**Comment by mgarciapatz** [comment]
i saw your new update and gets this error one after clicking update.
![godebugupdate](https://cloud.githubusercontent.com/assets/18435467/14549484/d3d47956-02f2-11e6-9b4a-7d4fca6aca3b.png)

**Comment by lloiser** [comment]
does the lines https://github.com/lloiser/go-debug/blob/master/lib/main.js#L25 and https://github.com/lloiser/go-debug/blob/master/lib/main.js#L47 are executed (set a breakpoint in the dev tools and reload atom using `alt-ctrl-r` or `cmd-alt-option-L`)? and whats the value of `p` in 47?

**Comment by mgarciapatz** [comment]
Sorry how can  I set a breakpoint? Not familiar with this Editor.

**Comment by lloiser** [comment]
like in chrome developer tools - click the line number in the "Sources" tab --> a blue arrow should appear

**Comment by valeros** [comment]
Hi @lloiser 
I'm having the same error with my newly installed Atom 1.7.2 on WMs with Ubuntu `14.04` and `15.10`
None of the lines mentioned above are reached in debug.
Thanks!

**Comment by lloiser** [comment]
sry the lines have changed in the meanwhile:
[main.js:15](https://github.com/lloiser/go-debug/blob/master/lib/main.js#L15) `dependenciesInstalled = true;`
[main.js:37](https://github.com/lloiser/go-debug/blob/master/lib/main.js#L37) `path = p;`

most likely `p` will be `false` or something else but not the path to the dlv executable...

**Comment by valeros** [comment]
Strange, but I can't reach these two lines if they both enabled (only `main.js:15` executed), but if I set only `main.js:37` then `p: false`.

**Comment by lloiser** [comment]
this means that go-debug cannot find the dlv executable... is it in your GOPATH?

**Comment by valeros** [comment]
It is in my `PATH`: `/home/valeros/goworkspace/bin` and I can run `dlv debug` in terminal.

**Comment by lloiser** [comment]
is the GOPATH also set for atom -> open the developer tools in atom and enter `process.env.GOPATH`. What's the value?

**Comment by valeros** [comment]
Hmm, `process.env.GOPATH` is undefined, but `echo $GOPATH` is `/home/valeros/goworkspace` and I can see `GOPATH=/home/valeros/goworkspace` in output from `printenv`

**Comment by lloiser** [comment]
ok, so atom does not know the GOATH. Maybe the way you start atom doesn't propagate the GOPATH to atom. Most likely happens if you start it from e.g. an desktop icon, so an environment which might does not know about GOPATH either... 
On my mac I have added the GOPATH to my `.bash_profile`...

**Comment by valeros** [comment]
Yep, I was starting it from the icon, now launching `Atom` directly from terminal helped!
Thanks for your time.

**Comment by venkykuberan** [comment]
Hello IIoiser,
  I am sorry for opening the can again. I have tried the above steps but failed to get go-debug working in my atom editor. **I can't setup breakpoints** but i do see Test/Debug panel on the right side. When i click on debug tab i get the following error on the output

**Delve output: 2016/08/11 23:37:46 server.go:71: Using API v1
2016/08/11 23:37:46 debugger.go:61: launching process with args: [./debug]
Delve output: could not launch process: could not fork/exec
delve closed with code 1**

Also "process.env.GOPATH" shows my go workspace folder and breakpoints in main.js are reaching.

Clicking on Test tab i get the following error

Delve output: 2016/08/11 23:43:39 server.go:71: Using API v1
**2016/08/11 23:43:39 debugger.go:61: launching process with args: [./debug.test]
could not launch process: stat /Users/x3g5/Venky/go/src/github.com/x3g5/rabbitmq/producer/debug.test: no such file or directory
delve closed with code 1**

I appreciate your help

**Comment by lloiser** [comment]
Hey @venkykuberan can you verify that delve is working the command line using `dlv`?

**Comment by venkykuberan** [comment]
@lloiser dlv is working in command line. I get this error only in atom for debug
Delve output: could not launch process: could not fork/exec

**Comment by venkykuberan** [comment]
@lloiser any idea why i go-debug is throwing me this error

Delve output: 2016/08/11 23:37:46 server.go:71: Using API v1
2016/08/11 23:37:46 debugger.go:61: launching process with args: [./debug]
Delve output: could not launch process: could not fork/exec
delve closed with code 1

**Comment by lloiser** [comment]
Is there any `debug` file in the same directory? These are left overs from previous debug sessions and might cause such an error.

**Comment by lloiser** [comment]
Or do you have installed dlv manually (including the certificate stuff)? If so try deleting the dlv executable and reload/restart atom then go-debug will take care of getting a valid dlv executable.

**Comment by venkykuberan** [comment]
I installed dlv through homebrew earlier. Getting dlv executable from go-debug after deleting the existing dlv executable helped. Thank you very much

**Comment by tommiv** [comment]
I'm not sure if I should join this conversation or create my own. In my case atom doesn't even try:

- no button to run debugger in the panel ![](https://i.imgur.com/TwUCKYI.png)
- no any messages in atom dev console, nor errors/stacktraces, nothing about go at all
- dlv is installed via brew (`which dlv => /usr/local/bin/dlv`)
- I've put this path to dlv manually in package config
- manual start of `dlv debug` works ok, BUT it shows graphic sudo password prompt
- F5 shortcut does lines sorting instead of starting debugger

I don't know where should I start, the other guys at least got an error messages.

**Comment by lloiser** [comment]
There is a second panel on the right which can be toggled with the command `Go Debug: Toggle Panel` (`ctrl-k ctrl-g` or `cmd-k cmd-g`)

**Comment by tommiv** [comment]
Well, it's cool, but I suppose I will see it when debugging session will start. Anyway, I opened it by hand and start/options buttons are disabled. They renders cursor with "deny" sign. Too bad, I cannot capture it with screenshot tool, but I guess you know what I mean, the one with striked cirle Ø.

Still no any errors in the console. A few filtered messages are from `sync-settings` package and they contains sensitive info. The red exceptions are from `go-plus package` – strange error in godoc, when I'm asking about function definition. Related to go, but unrelated to the `go-debug`.

![](https://i.imgur.com/Ou5iK0z.png)

**Comment by lloiser** [comment]
You have to "Select a config" in the combo box next to the start button.

**Comment by tommiv** [comment]
Oh wow. It works:
![](https://i.imgur.com/zq52zZh.png)
But I believe it must be said in readme. I see a huge amount of info that you _can_ do an _additional_ config, but I don't see any info that I _must_ choose from some predefined stuff. Also I was expected that quick command `Go Debug: start` will start with default config or **at least** will show an error box like "nothing to run, select a config first". Thank you for your help!

**Comment by benechols-wf** [comment]
I just had the same issue as @tommiv - It would be nice to have a useful error when you haven't selected a config and a note that you have to press a separate key combo to open the debugging panel (and that the debug panel in go-plus isn't all you need)

**Comment by lloiser** [comment]
With [`v1.1.0`](https://github.com/lloiser/go-debug/releases/tag/v1.1.0) a text is shown in the output panel on the bottom that you have to select a configuration in the debug panel on the right.

**Comment by chenpdx** [comment]
the go-debug works for me but I have a hard time figuring out how to run the debugger with command line arguments. Simply put, I don't know how to configure the debugger to read the debug.json file I provided., which has the follolowings:
{
  "configurations": [
    {
      "name": "Debug cmd",
      "mode": "debug",
      "cwd": ".",
      "args": [
        "-j",
        "config.json"
      ]
    }
  ]
}

**Comment by lloiser** [comment]
@chenpdx from the [Configuration section in the README](https://github.com/lloiser/go-debug#configuration)
> It's possible to create additional configurations by creating a file and setting the path in the `go-debug` setting `Configuration File`. You can even specify multiple configurations by separating the paths in this setting with commas. Relative paths will be resolved relative to the current project.

So just add the relative/absolute path to this debug.json file in the `Configuration File` setting of go-debug

**Comment by chenpdx** [comment]
Never mind, I figured it out.

**Comment by sciencefyll** [comment]
`
Started delve with config "Debug"
Adding breakpoint @ githubreader/Commitor.go:68
Adding breakpoint @ githubreader/Commitor.go:68 failed!
  Error: no code at /home/anders/go/src/github.com/sciencefyll/IMT2681-1/githubreader/Commitor.go:68
Starting delve with config "Debug"
Failed to start delve with config "Debug"
  Error: Error: Already debugging!
`

Not sure if this was the best place to share it.
