### ISSUE TITLE
Not able to set Breakpoints

### ISSUE THREAD

**Issue by stvnwrgs** [lloiser/go-debug#2]
I tried to set a breakpoint by clicking on the gutter(line numbers) but it did not worked. I disabled all plugins and tried again. Same behavior. I saw the function in the code but it is just not working. 

Sorry that i dont have any further infos. If you need something specific just tell me.

**Comment by stvnwrgs** [comment]
Now it is working for some reason. Cant explain why, restarted everything a few times before.

**Comment by lloiser** [comment]
maybe to find the reason, can you provide the go code and the version of delve you were using?
