### ISSUE TITLE
Set breakpoints not aligned with current click point

### ISSUE THREAD

**Issue by britannic** [lloiser/go-debug#22]
go-debug 0.1.9
Atom 1.7.2
OS X El Capitan 10.11.4
go version go1.6 darwin/amd64
Delve Debugger
Version: 0.11.0-alpha
Build: f454207a340cc6b16b69f5924c647938b3c1a771

Setting a breakpoint in go package, doesn't align with the line that was originally clicked.

For example in the attached link to a png file, I clicked the breakpoint at line 310, but the breakpoint was set for 317. To clear the breakpoint at line 317, I have to click on line 310 again.

[Screenshot](https://www.dropbox.com/s/fn5r7ug57q99c33/Screenshot%202016-04-20%2010.47.35.png?dl=0)

I cannot reproduce this behavior on smaller, less complex files that don't have types, structs and multiple comments etc.

**Comment by lloiser** [comment]
Sry, but I am not able to reproduce this with > 500 lines. Honestly I don't think it is related to the file itself but rather how you interacted with this file. Like copy/paste, executed other atom packages that modified that code, etc... Stuff like that. Can you please provide more about this then.

Also the list of currently installed packages might help. `apm list --installed --bare`

**Comment by britannic** [comment]
I was able to reproduce it using a simple "Hello" go program:

`package main

import "fmt"

func main() {
	fmt.Println("Hello World")
}`

I set a breakpoint on fmt.Println by clicking in the gutter at line 6 and then clicked "continue" to the breakpoint, then "step" into it. Then I tried to set a breakpoint in "iface.go" at line 129,  the package file called by stepping into fmt.Println and reproduced the behavior. Here is a [screenshot](https://www.dropbox.com/s/atl9ypq1zaibohj/Screenshot%202016-04-20%2013.13.24.png?dl=0)

**Comment by lloiser** [comment]
ok, got it! It happens only if you wrap your long lines (the ones with a dot instead of the line number)

**Comment by britannic** [comment]
Thanks very much for the quick bug fix @lloiser, I confirm the fix works on my system as well. Note, Atom needs to be restarted for the update to take effect.
