### ISSUE TITLE
Need a method to delete breakpoints, if a file is renamed or deleted

### ISSUE THREAD

**Issue by britannic** [lloiser/go-debug#23]
To reproduce the issue:

1. set a breakpoint in a go file
2. don't clear the breakpoint
3. delete or rename the file
4. click the original breakpoint in the debug panel
5. a new file will be created with the original name
6. if the breakpoint isn't on line 1, then the only way to remove the breakpoint will be to add a line, which will reset the breakpoint line number to current line.
7. if there were multiple breakpoints in the original deleted or renamed file, then attempting to remove them with the mouse results in [issue #21](https://github.com/lloiser/go-debug/issues/21)

Behavior shouldn't be to create a new file, instead it should warn that the file doesn't exist and offer to clear the breakpoint(s) from the debug tab.

Preferably it should be possible for all breakpoints to be cleared from the debug panel using the mouse or shortcut, in addition to locating and clearing them from the gutter.

**Comment by lloiser** [comment]
Added both the remove button for breakpoints in the panel and a warning if you click on such breakpoints:
![image](https://cloud.githubusercontent.com/assets/3003233/14725035/eed35a84-0819-11e6-8823-a1cb848aaca3.png)
