### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by britannic** [lloiser/go-debug#25]
[Enter steps to reproduce below:]

1. Open a file
2. Resize the Go-Debug panel
3. Uncaught TypeError pops up

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package, v0.1.11

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

```
At /Users/Neil/.atom/packages/go-debug/lib/panel.jsx:261

TypeError: Cannot read property 'getBoundingClientRect' of null
    at Panel.onResize (/Users/Neil/.atom/packages/go-debug/lib/panel.jsx:261:33)
```

### Commands

```
     -0:03.2.0 minimap:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "travis-ci-status"
    ],
    "packagesWithKeymapsDisabled": [
      "markdown-preview"
    ],
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  },
  "go-debug": {
    "delvePath": "/usr/local/go/bin/dlv",
    "limitCommandsToGo": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-go, v1.0.6
builder-go, v1.0.0
change-case, v0.6.0
color-picker, v2.1.1
compare-files, v0.6.2
emmet, v2.4.3
environment, v1.2.0
file-icons, v1.7.7
fonts, v1.2.0
go-config, v1.1.4
go-debug, v0.1.11
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-line, v0.11.1
javascript-snippets, v1.2.1
last-cursor-position, v0.9.0
linter, v1.11.4
linter-jsonlint, v1.2.5
markdown-preview-plus, v2.4.0
merge-conflicts, v1.4.2
minimap, v4.22.1
monokai-seti, v0.7.0
navigator-godef, v1.0.3
pigments, v0.26.0
tester-go, v1.0.4
vim-mode, v0.65.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by lloiser** [comment]
Any more details? Works for me for atom 1.7.2 and atom beta 1.8...

**Comment by britannic** [comment]
I can reproduce it, by doing the following:

1. Restarted Atom
2. Opened a Perl project (a nice feature would be for Go-Debug to hide/disable the panel on non-Go source files
3. Attempted to resize the Go-Debug panel's width to a smaller size
4. The panic is triggered 

You've done a great job with this addition to Atom's Golang support, thanks so much for all of your hard work!

**Comment by lloiser** [comment]
You actually can hide the panel --> see https://github.com/lloiser/go-debug#key-bindings
> `cmd-k cmd-g` (mac) / `ctrl-k ctrl-g` (others) toggles the main panel

I will try to reproduce it with a perl project then although I suspect it to be a problem.
Maybe some of your other packages affects it, I will check that too...

**Comment by britannic** [comment]
I found the keybindings didn't work as described, I had to use (Mac) cmd-k-g to toggle on and off.

**Comment by britannic** [comment]
Additional, I found that after the panel resize panic in a Perl project, toggling the Go-Debug panel on again and then resizing had no further errors.

**Comment by lloiser** [comment]
Ok, so after a panel toggle it works. Strange... Does it still work after a restart and atom close/open?
Tbh: I can't imagine how this could have helped... :confused:

**Comment by britannic** [comment]
Yes, after toggling the panel on/off/on, cmd-q and restarting Atom, it works fine.
