### ISSUE TITLE
Passing command line arguments

### ISSUE THREAD

**Issue by rossmcf** [lloiser/go-debug#26]
I can't see a way to pass arguments to my program when debugging, i.e. using the -- args from the CLI. Is the functionality hidden somewhere?

**Comment by lloiser** [comment]
Right below the "Test" and "Debug" buttons is a little input with the placeholder text "arguments passed to delve after --"

**Comment by rossmcf** [comment]
Thanks for the quick response. I don't seem to have the input you mention (see screenshot). I'm running Atom 1.7.2 and go-debug 0.1.11.

![go-debug](https://cloud.githubusercontent.com/assets/94686/14845898/ed52be46-0c58-11e6-8ed2-3f2f908554c5.png)

**Comment by lloiser** [comment]
It's in there since 0.1.7. Are you sure that you already have 0.1.11? I can see 21 pending updates in your atom...

**Comment by rossmcf** [comment]
I was definitely on 0.1.11. Looking at the Updates panel didn't show any pending updates to go-debug. Oddly, running Update All sorted the problem. I have no idea what just happened.

Thanks for your help anyway!

**Comment by fetzerms** [comment]
I do not see the args in the current version. Has this been removed? Do I need to create my own config file and set the args there?

**Comment by lloiser** [comment]
Yes this has been removed. Here is an [example](https://github.com/lloiser/go-debug#examples) on how to apply arguments now.

**Comment by amit-handa** [comment]
I passed the config in the settings of 'go-debug'. passed the args there. however, delve starts 'debug' without any of these arguments. how do I fix it ?
