### ISSUE TITLE
Unable to Select Text in Debug Frame

### ISSUE THREAD

**Issue by eukota** [lloiser/go-debug#28]
Atom Version: 1.7.3
System: Windows 7 Pro 64-bit
From: go-debug package, v0.1.11

The variable list in the debug frame is nice but I want to be able to select and copy the data from within it. Although the cursor changes to a text-tool, I cannot select the text.

I did a little bit of reading and there were mentions here (https://github.com/tcarlsen/atom-message-panel/issues/24) about setting the attribute "tabindex" to -1 helping enable text selection.

And this discussion (https://discuss.atom.io/t/cant-select-panel-text/15453) mentioned adding the "native-key-bindings" class to allow for copy and paste to work.

If I knew a bit more or had more time, I would try to do a pull request. Just logging the request for now.

**Comment by lloiser** [comment]
see v0.1.12

**Comment by eukota** [comment]
Awesome it works! Thanks!
