### ISSUE TITLE
Install delve Binaries For The User

### ISSUE THREAD

**Issue by joefitzgerald** [lloiser/go-debug#30]
Because delve is not go gettable on all platforms, on some platforms (e.g. OS X, Windows) a binary could be downloaded and installed to ease the user's first experience with this package.

* https://github.com/derekparker/delve/issues/494 is open for canonical delve releases to include binaries
* https://bintray.com/jetbrains/golang/delve/view is maintained by Jetbrains, and could be used in the interim

Conceptually, I think the code required to satisfy this issue would:

1. Check a location (the Jetbrains repo or the canonical repo) for versions
1. Use semver to determine the latest version
1. Download the binary
1. Place the binary in `$GOPATH/bin` (as determined using `go-config`)
1. Detect the location of the binary
1. Use the binary

There's an alternate flow for platforms (e.g. Linux) for which `delve` is go gettable: use `go-get` to prompt the user to `go get -u https://github.com/derekparker/delve`.

https://github.com/joefitzgerald/go-plus/pull/410 is blocked by this.

**Comment by lloiser** [comment]
good idea, I'm working on it!

**Comment by lloiser** [comment]
I have added a first version which just installs dlv only if it is not available. Windows and Linux are simply `go get`-able whereas mac downloads the latest version from the bintray you mentioned.
I will add an auto updater later!

**Comment by joefitzgerald** [comment]
:tada:
