### ISSUE TITLE
delve connect support

### ISSUE THREAD

**Issue by soulthani** [lloiser/go-debug#31]
Hi,

is it possible to have dlv connect possibility from go-debug ? so that we can debug go runtime remotely and change variables value at runtime with go-debug in atom.

**Comment by pavel-odintsov** [comment]
I'm also interested in remote debugging because my application is not working at Mac OS and I need to use Linux VM each time. So I could not use shiny debugging feature from Go-Debug :(

**Comment by joefitzgerald** [comment]
See also #49. Worth mentioning: you can run Atom on Linux also, if you have a windowing environment on your Linux VM.

**Comment by lloiser** [comment]
It is possible to define [configurations](https://github.com/lloiser/go-debug#configuration) with the latest version (`v1.0.0`).
These configurations also include a `mode` to `connect` to a headless delve running somewhere else. Also add `host` and `port` to specify the (delve) endpoint you started delve with.
