### ISSUE TITLE
environment vars under Test

### ISSUE THREAD

**Issue by eduncan911** [lloiser/go-debug#35]
Thank you for the integration with Atom.  Though I haven't needed a debugger for Go for years, today is the day I take on a huge unknown codebase and immediately need to debug/follow-through some failing tests.

**How would one set environment variables to debug under `Test`?**  I need to set a number of CLI environment vars for the integration tests.  

I see a textbox under the TEST and DEBUG tabs that says "arguments passed to delve after --".  Looking at the [delve CLI docs](https://github.com/derekparker/delve/tree/master/Documentation/cli), I didn't see a way to specify environment variables though.

**Comment by lloiser** [comment]
Unfortunately this is not possible yet... 
But you could set them in the your terminal and launch atom from there so atom (and therefore dlv) inherit the same environment variables.

**Comment by eduncan911** [comment]
Hey, that kinda worked!  (setting `env` vars and launching Atom).  though i can see the breakpoint hit in the Goroutines list (shows the line number it stops on while highlighting the method I put a breakpoint into), it doesn't show any vars and it doesn't allow me to step into.

Is Debugging supposed to allow stepping into?  May just be the complexity of the project and packages that it `delve` is having issues with.

Thanks!  Will close.

**Comment by lloiser** [comment]
> it doesn't show any vars and it doesn't allow me to step into

no variables? not able to step into (using the button in the panel or F11)? this sounds like a bug! do you see any errors in the developer tools in atom (alt-ctrl-i on win, alt-cmd-i on mac)
