### ISSUE TITLE
Conditional breakpoints support

### ISSUE THREAD

**Issue by xphoenix** [lloiser/go-debug#36]
It seems that delve support conditional breakpoints: by hit count & by expression. It would be nice to have support for that feature in UI

**Comment by lloiser** [comment]
Done in [`v1.1.0`](https://github.com/lloiser/go-debug/releases/tag/v1.1.0). Simply right click the breakpoint in the gutter or in the panel and select `Edit Breakpoint Condition` in the context menu.
