### ISSUE TITLE
f5 shortcut does absolutely nothing

### ISSUE THREAD

**Issue by mtitolo** [lloiser/go-debug#37]
Just installed go-debug for the first time, after downloading the newest Atom on Mac OS X 10.11.3.

I have keyboard shortcuts enabled, but f5 does absolutely nothing. Nothing is output to the console.

The only way I can run/debug is to click the "Debug" area of the sidebar, wait for a bunch of errors to be printed, and then use the controls up there. Debug gets unselected after each run, so the console just gets a lot of these. At no point in time does f5 do anything, regardless of whats selected.

Not sure if the error from Delve are related? Putting them here in case they are.

```
Starting delve with "/Users/michele/Projects/go/web-playground/main.go" with "debug"
Delve output: 2016/07/01 17:00:55 debugger.go:55: launching process with args: [./debug]
Started delve with "/Users/michele/Projects/go/web-playground/main.go" with "debug"
Delve output: 2016/07/01 17:00:55 server.go:301: method Run has wrong number of ins: 1
2016/07/01 17:00:55 server.go:301: method Stop has wrong number of ins: 2
```

**Comment by lloiser** [comment]
please open the `Key Binding Resolver:Toggle` from the command palette. A small panel at the bottom should appear. This shows which commands are triggered if a certain key (combination) is pressed.
Whats happening for F5 and the other keys the go-debug package provides?

**Comment by mtitolo** [comment]
It is only bound to go-debug, but still doesn't do anything.
![screen shot 2016-07-07 at 8 21 41 am](https://cloud.githubusercontent.com/assets/763698/16658626/e58fbfe2-441b-11e6-94d5-08985018e2bf.png)

**Comment by lloiser** [comment]
I'm sorry but I don't know how this could fail, the code is really simple. Both the `f5` key and the `Debug` button use almost the same code...

Which version of atom and delve (`dlv version`) are you using?

Can you try and debug it? Open the dev tools with `cmd alt i`. It starts here https://github.com/lloiser/go-debug/blob/master/lib/commands.js#L27 which calls https://github.com/lloiser/go-debug/blob/master/lib/delve.js#L21

**Comment by JonnyPillar** [comment]
Im also seeing this issue. Installed go-debug fine through the packages panel in atom, the key-binds are active and display in the Key Binding Resolver but the commands like toggle-panel and run-package seem to be unresponsive. There are no errors output in the dev console. 

Im new to debugging packages though. Cant find the package in the console sources. The only files I can find are: 

![screen shot 2016-07-11 at 11 41 19](https://cloud.githubusercontent.com/assets/12187067/16728564/fd0691aa-475e-11e6-9031-b976412c86f5.png)

Im running Atom 1.8.0 on Mac and running Deleve Build: v0.11.0. Delve runs fine from the command line.

**Comment by lloiser** [comment]
Weird I can see it in my fresh atom installation:
![screen shot 2016-07-11 at 14 09 57](https://cloud.githubusercontent.com/assets/3003233/16730114/48c51c6c-4771-11e6-8920-339aee613111.png)
Try starting atom in development mode using `atom --dev`

**Comment by JonnyPillar** [comment]
Ok I think I may have an idea. I believe the package files not being shown is a bit of a red herring.

I have stuck a breakpoint here https://github.com/lloiser/go-debug/blob/master/lib/main.js#L61 and enabled the package in Atom. `path` is set as undefined so in simply returns.

The function `getDlv` never gets called and path doesnt get set. 

Any thoughts on why that would happen?

**Comment by lloiser** [comment]
On first sight I can't imagine why `getDlv` is not called...
Check your packages if both `go-get` and `go-config` are installed and enabled.

**Comment by JonnyPillar** [comment]
Got it, `go-get` failed on being enabled. Uninstalling and reinstalling and it instantly started working.
Thanks for your help @lloiser

**Comment by JonnyPillar** [comment]
@mtitolo Maybe worth checking `go-get` is installed/enabled

**Comment by mtitolo** [comment]
@JonnyPillar I reinstalled `go-get` and restarted Atom. No change except now the side panel won't show up. I tried turning off the "only use commands for go files" setting, and it still doesn't show up.

I have restarted Atom multiple times and uninstalled/reinstalled `go-debug`. Neither `cmd-k cmd-g` nor `f5` work, and I can't open the debug panel. I can't test other keybindings since I need to debug an application to use them.

**Comment by lloiser** [comment]
You can toggle the using the `Go Debug: Toggle Panel` command in the commands palette.
Maybe also open atom in development mode using `atom --dev` and check if there are any errors.
Also add some breakpoints to the files I mentioned previously and check if they get called when you hit f5:
> It starts here https://github.com/lloiser/go-debug/blob/master/lib/commands.js#L27 which calls https://github.com/lloiser/go-debug/blob/master/lib/delve.js#L21

**Comment by mtitolo** [comment]
There is no option for Go Debug in the command palette. I've uninstalled and reinstalled several times. I've restarted Atom multiple times. It's enabled. No command palette commands. No side panel.

I think something is up with my Atom install. There is no commands.js file in the package.
![screen shot 2016-07-14 at 7 12 14 pm](https://cloud.githubusercontent.com/assets/763698/16861583/ed8bb530-49f6-11e6-8ae1-695d2c00bfcc.png)

**Comment by lloiser** [comment]
Looking at https://github.com/lloiser/go-debug/blob/master/lib/main.js#L65-L75 you can see that I require most of the stuff (also commands.js) once I'm certain that everything else is ready. That's probably your problem.

Make sure both the package `go-get` and `go-config` are installed and enabled.

If so and it still does not work, add breakpoints to the following lines and tell me which one is not called:
https://github.com/lloiser/go-debug/blob/master/lib/main.js#L16
https://github.com/lloiser/go-debug/blob/master/lib/main.js#L37
https://github.com/lloiser/go-debug/blob/master/lib/main.js#L41
https://github.com/lloiser/go-debug/blob/master/lib/main.js#L53 (note: if you have not installed delve yet this line might take some time until it is reached)

**Comment by mtitolo** [comment]
After a lot of headache, and some other weird things in Atom, I just reinstalled Atom fully and now it works. That first "activate" breakpoint wasn't even getting hit ¯\_(ツ)_/¯

**Comment by BroLiammoji** [comment]
Check to see that Terminal isn't just minimized!  That was my problem..
