### ISSUE TITLE
Debugger does not stop when Atom quits

### ISSUE THREAD

**Issue by mtitolo** [lloiser/go-debug#40]
This drove me mad a few days ago. When I have an app running and attached to the debugger, the debugger will not quit when Atom quits. The application being debugged does quit appropriately.

```
$ ps ax | grep dlv
15577   ??  S      0:00.24 /usr/local/bin/dlv debug --headless=true --listen=localhost:2345 --log
```

When Atom is restarted and I try to debug an application, this message prints:
```
couldn't start listener: listen tcp 127.0.0.1:2345: bind: address already in use
delve closed with code 1
```

The debugger should quit when Atom quits. Since it does not, the process keeps running and no further applications can be debugged until the process is killed via the command line.

**Comment by lloiser** [comment]
see #38
