### ISSUE TITLE
Input in main window

### ISSUE THREAD

**Issue by pwolf23** [lloiser/go-debug#41]
Hi,

thanks for the great plugin... debugging contributes greatly to the value of atom as go ide... however: how am I supposed to debug something like this?

```
package main

import "fmt"

func main() {
	var a int
	fmt.Scanf("%v\n", &a)
	fmt.Printf("%v", a)
}
```
The Scanf blocks until it receives some input. How can I provide input?

**Comment by lloiser** [comment]
This does not work in the command line tool itself, so it won't work here either!
see https://github.com/derekparker/delve/issues/65
