### ISSUE TITLE
Test & Run pane disappear

### ISSUE THREAD

**Issue by jeromelaurens** [lloiser/go-debug#5]
Hi,

I have a new problem on MacOSX with the latest version ::
When I open atom and a go file, the test&run Pane is there, but whatever I do on this Panel it disappears.
The simplest action to make this happen is to click on "Toggle output Panel" : the output displays, but the test&Run panel disappears.

My Delve installation is working (version 0.11.0-alpha, build cfe0e52d040955efc34e7b34ef41313f03fe4864), and the delve path in go-debug is correct.

It used to work before, but I'm not sure of when it has been broken.

Launching atom --dev and looking at the console does not show anything.

Thanks for your help.
Jerome

**Comment by lloiser** [comment]
Have you tried to uninstall, close and open atom and install it again? It solved a problem with another package I used some time ago...

**Comment by jeromelaurens** [comment]
I did it : no effect :(

**Comment by lloiser** [comment]
I have added a keybinding to toggle the panel `ctrl-k ctrl-g` (visible in the settings of my package, also in the command palette as "Go Debug: TogglePanel")
If this doesn't help either:
Do you see *any* messages/errors in the developer tools console (in dev mode)?
Which other packages are installed? Open a cmd and run `apm list --installed --bare`. Maybe there is a conflict or so...

**Comment by jeromelaurens** [comment]
Nice !
the toggle action gave me again the panel, and it stays opened.
FYI on my MAC I've setup the keymap as ctrl-k is already used
```
'atom-text-editor':
  'cmd-k cmd-g': 'go-debug:togglePanel'
```
Thanks for your help

**Comment by lloiser** [comment]
ah interesting, I will change the binding then here because the tree view package also uses cmd on mac and ctrl on win.

**Comment by lloiser** [comment]
-> ab8dbdb478b109ceb9c7581398426448729583be
