### ISSUE TITLE
adding verbose mode to tests output

### ISSUE THREAD

**Issue by ramigg** [lloiser/go-debug#57]
Hi,
Very nice work you've done. It would be great to have a verbose flag option in settings for testing.

thanks.

**Comment by lloiser** [comment]
It is possible to define [configurations](https://github.com/lloiser/go-debug#configuration) with the latest version (`v1.0.0`).
These configurations also include `args` which will be passed through to the tests/application you are debugging. (there is even an [example](https://github.com/lloiser/go-debug#examples) it the README 😉 )
