### ISSUE TITLE
Variables list not refreshing

### ISSUE THREAD

**Issue by ylamothe** [lloiser/go-debug#58]
Hi,

I'm currently running a go program which runs as a daemon (Swagger server). When running an API call, I can see a new go-routine associated with my thread, breaking at the right line. Nexting is working fine as I can see line # increasing in go-routines. However, variable list is not refreshed. Switching to another go-routine actually refreshes the list, but coming back to my thread does not solve the issue.

The developer log is giving the following error:

```
delve-variables.js [sm]:83 Uncaught (in promise) TypeError: Cannot read property 'onlyAddr' of undefined
    at Object.ptr (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:83:14)
    at Object.variable (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:54:23)
    at Object.map (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:182:51)
    at Object.variable (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:54:23)
    at /Users/me/.atom/packages/go-debug/lib/delve-variables.js:146:43
    at Array.map (native)
    at Object.struct (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:145:40)
    at Object.variable (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:54:23)
    at /Users/me/.atom/packages/go-debug/lib/delve-variables.js:146:43
    at Array.map (native)
    at Object.struct (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:145:40)
    at Object.variable (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:54:23)
    at /Users/me/.atom/packages/go-debug/lib/delve-variables.js:26:23
    at Array.map (native)
    at Object.create (/Users/me/.atom/packages/go-debug/lib/delve-variables.js:25:16)
    at /Users/me/.atom/packages/go-debug/lib/delve.js:239:38
    at Array.forEach (native)
    at prepareVariables (/Users/me/.atom/packages/go-debug/lib/delve.js:238:14)
    at /Users/me/.atom/packages/go-debug/lib/delve.js:232:5
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I'm using go-debug v0.1.22 along with the following version of delve:

```
Delve Debugger
Version: 0.11.0-alpha
Build: v0.11.0
```

Any clue on what's happening, or any idea on specific things to check?

Thanks,
Y

**Comment by lloiser** [comment]
Can you try to create a minimal sample to reproduce this problem?

**Comment by ylamothe** [comment]
Sure...
The attached code is a minimalistic swagger implementation. You can launch the server by debugging cmd/test-server/main.go (use --port 8080 to launch it on port 8080). I'm having a breakpoint on line 41 in restapi/configure.go.

Using a tool like postman, you can then trigger a POST on http://localhost:8080/v1/test and use the following payload:
```json
{
  "testID": "1234",
  "testName": "first test"
}
```

You should get an uncaught (in promise) type error as described above.
Hope you will be able to reproduce.

[swaggertest.zip](https://github.com/lloiser/go-debug/files/528891/swaggertest.zip)

**Comment by lloiser** [comment]
I'm really sorry but I cannot reproduce this using the code you provided... Nevertheless I will fix it so it at least won't fail.

**Comment by ylamothe** [comment]
Thanks for the update. Maybe linked to my environment then, even though I'm running all latest versions...

**Comment by alexandernst** [comment]
I have the exact same issue. Test is very simple, just clone https://github.com/blang/semver and create a breakpoint in `range.go` at line `90` (right after `func ParseRange`). After hitting "Next" one time, the `parts`variable doesn't appear in the list of variables in the go-debug panel.

**Comment by lloiser** [comment]
Unfortunately I'm not able to reproduce this. Neither on windows 10 nor on ubuntu 16.04 with latest `dlv`.

![image](https://cloud.githubusercontent.com/assets/3003233/22186207/2ddaa42e-e0f2-11e6-8fbf-63d463732591.png)

![image](https://cloud.githubusercontent.com/assets/3003233/22186209/32cc926c-e0f2-11e6-8ba7-aed890da173a.png)

Is there any error in the atom dev tools? Open it with the command `Toggle Dev Tools`.

Also make sure you are using the latest dlv. On windows and linux you can simply remove the `dlv` executable from your `$GOPATH/bin` folder. go-debug should install it if it cannot find it. If you are on mac either remove it from your bin folder too or update your brew installation.

**Comment by lloiser** [comment]
At lot has changed since then. Feel free to reopen if this is still a problem.
