### ISSUE TITLE
Toggle pane visibility

### ISSUE THREAD

**Issue by pkieltyka** [lloiser/go-debug#6]
This is incredible work, thank you for making it! could there be a hot-key for hiding/showing the pane?

**Comment by lloiser** [comment]
the pane with the stacktrace/variables? `ctrl-k ctrl-g` (will change it on a mac to `cmd-k cmd-g`)

**Comment by pkieltyka** [comment]
@lloiser thanks that works well. You should add that to the README, along with any other tips

**Comment by lloiser** [comment]
-> ab8dbdb478b109ceb9c7581398426448729583be
