### ISSUE TITLE
Deprecated selector in `go-debug/styles/go-debug.less`

### ISSUE THREAD

**Issue by lukasredynk** [lloiser/go-debug#60]
In `go-debug/styles/go-debug.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
- `atom-text-editor::shadow .go-debug-gutter-breakpoint` => `atom-text-editor .go-debug-gutter-breakpoint`
- `atom-text-editor::shadow .go-debug-breakpoint` => `atom-text-editor .go-debug-breakpoint`
- `atom-text-editor::shadow .go-debug-breakpoint-state-valid` => `atom-text-editor .go-debug-breakpoint-state-valid`
- `atom-text-editor::shadow .go-debug-breakpoint-state-invalid` => `atom-text-editor .go-debug-breakpoint-state-invalid`
- `atom-text-editor::shadow .go-debug-debug-line` => `atom-text-editor .go-debug-debug-line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by lloiser** [comment]
I have changed the styles to use both at the moment so it works for `< v1.13.0` too.
This issue stays open for now until `v1.13.0` will be released. Then I will remove the `::shadow` selector.

**Comment by mistadikay** [comment]
`1.13.0` released! https://github.com/atom/atom/releases/tag/v1.13.0

**Comment by ssarangi** [comment]
Hi, has this been fixed on 1.13.0 ? I still see the issue on this version...
