### ISSUE TITLE
go-debug doesn't work with any cgo library

### ISSUE THREAD

**Issue by michael-nischt** [lloiser/go-debug#61]
If importing any cgo library (e.g. "github.com/go-gl/gl/v4.5-core/gl") executing works but debugging doesn't with the following error:

Delve output: could not launch process: Unreadable version number: could not read string len input/output error

It's probably related to this issue: https://github.com/derekparker/delve/issues/477
So maybe someone can add the workaround using `-ldflags="-linkmode=internal"` to go-debug?

**Comment by lloiser** [comment]
It is possible to define [configurations](https://github.com/lloiser/go-debug#configuration) with the latest version (`v1.0.0`).
These configurations also include `buildFlags` which will be passed through to delve.
