### ISSUE TITLE
F5 / Start Broken - Cannot Find selectedConfig

### ISSUE THREAD

**Issue by m3-mwilliamson** [lloiser/go-debug#64]
Unable to start go-debug with F5 to start a debugging session.  This worked in earlier versions and has broken since upgraded to 1.0.0.

For some reason in the start command selectedConfig is always being set as "".
configurations contains the expected debug and test elements.

```const commands = {
  'start': {
    cmd: 'start',
    text: 'Start',
    title: 'Start this configuration',
    action: (store, dbg) => {
      const { selectedConfig, configurations } = store.getState()
      if (!selectedConfig) {
        return // no config to start
      }
```

Is there any reason why it would not be able to find a config to start?  This happens on OSX El Cap and Sierra.

Thanks!

**Comment by lloiser** [comment]
Have you noticed that the debug panel has slightly changed?
![image](https://cloud.githubusercontent.com/assets/3003233/21423917/dc5eaa02-c83f-11e6-92e7-fd608af8a4af.png)
It now contains a combo box where you can select which [configuration](https://github.com/lloiser/go-debug#configuration) to start. By default this is set to "Select a config" which means no configuration is selected. Just click the combo box and select either "Debug" or "Test". These are the same commands as there has been before with `F5` (Debug) and `ctrl-F5` (Test). You can also add custom configurations (mentioned in the [README](https://github.com/lloiser/go-debug#configuration))

**Comment by m3-mwilliamson** [comment]
Ah, thank you.  All is good now.  Previously I think this panel showed up automatically when hitting F5? 

So it looks like my panel was hidden since the upgrade and I never manually toggled to display it to set the new config option on first run.

Thanks!
