### ISSUE TITLE
go debug is not able to stop

### ISSUE THREAD

**Issue by rjboer** [lloiser/go-debug#65]
go-debug starts wel, but does not respond to the stop button. 
trying to remove breakpoints at that point won't remove breakpoints, looks like the application "hangs", 
Occurence: ever since the update to 1.0 (did not occur in earlier versions)
how to reproduce, add a couple of breakpoints to a go script, start debugging, after go-debug reaches the first breakpoint, press the stop button... this does not work

**Comment by lloiser** [comment]
Please copy & paste the content of the `Debug` tab in the `go-plus` panel (it opens whenever you start the debugger)
Also provide some source code if possible.

**Comment by UksKim** [comment]
me too...

**Comment by lloiser** [comment]
Update to `v1.0.1`
