### ISSUE TITLE
Debugger detaches after starting

### ISSUE THREAD

**Issue by acatighera** [lloiser/go-debug#67]
I am using latest Atom (1.12.7) with go-plus (5.0.9) and go-debug (1.0.2). After starting a debug session I see the follow in session log:

```
Starting delve with config "Debug"
API server listening at: 127.0.0.1:2345
Started delve with config "Debug"
```

There is nothing in debugger console. When I stop or restart it seems that the session is no long attached. The process is still running. As an additional note: break points don't work at all.

I am on Ubuntu 16.04.

**Comment by lloiser** [comment]
Can you try and run your program using `dlv` in the command line so we can see if it is a problem with delve or with go-debug.

**Comment by acatighera** [comment]
It's looking like it is a delve issue, any recommendations? There are issues debugging via command line as well.

**Comment by acatighera** [comment]
I had to manually build dlv with `make install` with the latest clone of their master. Weirdly, I couldn't do a manual build until after I ran `go get github.com/derekparker/delve/cmd/dlv`. I think the problem was that they haven't pushed out a release in quite a while, so I had to manually build the latest code.

**Comment by acatighera** [comment]
So I have been able to reproduce the issue, I have more information on how to do it. It seems as though the "stop" button only works if there is a breakpoint. If there are no breakpoints and the debugger is running, the "stop" button will simply detach without stopping the debug session/server.
