### ISSUE TITLE
Can't get configurations to work

### ISSUE THREAD

**Issue by azethoth** [lloiser/go-debug#68]
I can't seem to get configurations to work. I created a simple test config:

```
{
  "configurations": [
    {
      "name": "Verbose Test",
      "mode": "test",
      "args": ["-v"]
    }
  ]
}
```

and put this in ~/.godebug/config.json

then I set that location in the Configuration File setting. But I don't see it in the debugger config dropdown, just Debug and Test. I don't see any errors in the developer console. Any ideas?

**Comment by lloiser** [comment]
It seems it does not work with `~` right now. You could use the absolute path to your home dir as a workaround until I fixed this.
