### ISSUE TITLE
[feature-request] ability to source a file in configuration

### ISSUE THREAD

**Issue by primalmotion** [lloiser/go-debug#70]
In addition to being able to set env variables in the configuration files, it would be very helpful if we could source a file.

We are using source files containing a lot of variables holding config for various services, if we could used them, we will be able to have a single go-debug configuration for all our various services.

Thanks!

**Comment by lloiser** [comment]
multiple issues:
* no `source` on windows
* there is no way (that I know) to execute 2 commands using node and reusing the resulting env from the first command. It might work on unix like systems if I would try something like `source <file> && dlv ...` in one command but I haven't tried yet.

I'll think about this...

**Comment by ishmulyan** [comment]
@lloiser, sorry for bothering, I would really love to see this feature. Are there any ideas or progress with it?

**Comment by lloiser** [comment]
As a simple workaround would be to open your terminal, `source` anything you want and then open any directory in atom using `atom <path>`.

**Comment by primalmotion** [comment]
I guess this is outdated.Closing to cleanup my list of opened issues.
