### ISSUE TITLE
Stuck on last breakpoint

### ISSUE THREAD

**Issue by lukescott** [lloiser/go-debug#74]
I have:
- go 1.75 (installed with homebrew)
- atom 1.13.1
- go-debug 1.04
- delv 0.12.1

I have gotten the debugger running by opening the debug panel, selecting the "Debug" profile, then hitting "Run" while selecting my main.go file.

The bulk of my program is not in the main package, but rather in a "service" package in my project root.

Before running I place break-points within a function. When I hit "Continue" it goes to the next break-point. When I hit "Continue" on the last break-point the editor gets stuck on that breakpoint. The line continues to be highlighted, and all the information remains. However, it seems that the program does continue from that point, it just doesn't show it in the editor.

When looking at the demo animation, it does show that everything clears after continuing from the last breakpoint. But that doesn't seem to be working as demonstrated.

Here is the function I tested it on, if that matters:

```go
func (s *session) waitForClient(c *Client) *Client {
	s.m.L.Lock()
	defer s.m.L.Unlock()
	if s.c != c {
		return s.c
	}
	timeout := make(chan bool)
	timer := time.AfterFunc(
		time.Second*10,
		func() { timeout <- true },
	)
	go func() {
		if <-timeout {
			s.m.Signal() // breakpoint here
		}
	}()
	s.m.Wait() // <-- s.m is *sync.Cond
	if timer.Stop() {
		timeout <- false // breakpoint here
	}
	if s.c == c { // breakpoint here
		s.c = nil
	}
	return s.c // breakpoint here
}
```

**Comment by lloiser** [comment]
Yeah, I've noticed this already.

This happens if you start the debugger for a program that keeps running after you continue the last breakpoint, like a http server or a cli.
