### ISSUE TITLE
[feature request] a watch drop down

### ISSUE THREAD

**Issue by rgeddes** [lloiser/go-debug#76]
similar to the "Watch" in the Chrome Dev Tools to evaluate variables and expressions during a debug session

**Comment by lloiser** [comment]
Unfortunately [`delve`](https://github.com/derekparker/delve) does not really provide something like this. It has something similar called [`print`](https://github.com/derekparker/delve/tree/master/Documentation/cli#print) which lets you execute any code in the command line and print the result. This is not available in go-debug yet.

Would this be enough?

**Comment by rgeddes** [comment]
Ideally, having access to all scopes and their associated variable states is preferable.  This gives me what I call "scope awareness" and is helpful, in particular, when dealing with someone else's code.  My experience is that some coders explain their code in a way that is inconsistent with my observation, and the only way to resolve these situations is with a good debugger.

Javascript, C++, PHP, and Java debuggers I've used in the past ( with the eclipse ide/chrome dev tools ) do a good job of this.

A debugger is also a good learning tool, as it will confirm/refute my understanding of what the code is doing.

A print statement would definitely help.

**Comment by lloiser** [comment]
I'm currently adding a ["repl"](https://github.com/lloiser/go-debug/issues/88) to go-debug which pretty much uses the same functionality that would be required for this feature.

**Comment by lloiser** [comment]
see [`v1.3.1`](https://github.com/lloiser/go-debug/releases/tag/v1.3.1)
