### ISSUE TITLE
key binding cmd-k cmd-g does not open up the debug panel 

### ISSUE THREAD

**Issue by krishnaghatti** [lloiser/go-debug#80]
i am using atom:1.14.4 and go-debug:1.1.0
the key binding cmd-k cmd-g does not open up the debug panel. am i missing anything.

**Comment by lloiser** [comment]
If go-debug cannot find a `dlv` executable you won't be able to open the panel. It should also show an error in atom:

![screen shot 2017-03-03 at 08 21 53](https://cloud.githubusercontent.com/assets/3003233/23541939/b70b6866-ffea-11e6-8946-828a119da42b.png)

It looks for `dlv` in `GOPATH/bin` and `PATH`. Make sure you have it installed it correctly by following this guide https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md

**Comment by krishnaghatti** [comment]
thank you. the pop up for installing dlv package did not appear until i opened a new window. 
i am able to open the debugger now. closing the issue.
