### ISSUE TITLE
No keymappings

### ISSUE THREAD

**Issue by jyutzler** [lloiser/go-debug#83]
OSX 10.11.6
Atom 1.15.0 x64
dlv 0.12.1 available at /usr/local/bin/dlv (installed through Homebrew)
go-debug 1.1.0 claims to be installed but no key mappings are installed. There is nothing go-debug related in the keybindings list.

Nothing shows up at the console log at all, even when I run in debug mode.

This is probably something simple but I have no idea what it could be.

The only indication that I can find that this is working at all is that I can click in the margin of a file and get a little red circle. I don't see how to use this tool without the keyboard bindings.

**Comment by lloiser** [comment]
The main debug panel is hidden initially. You can open it via `cmd-k cmd-g`. Then select whether you want to debug "main" (choose "Debug") or debug tests (choose "Test").

You can also simply hit `F5` to start a debug session. It will also open the debug panel.

**Comment by jyutzler** [comment]
No. None of those commands do anything. Again, there is nothing go-debug related in the keybindings list. Uninstalling the go-debug plugin and reinstalling has no effect.

**Comment by lloiser** [comment]
It is possible to disable _all_ keybindings in the settings of a package. Make sure this checkbox is checked in the settings of go-debug.

![image](https://cloud.githubusercontent.com/assets/3003233/23918612/ffc410fa-08f3-11e7-9f51-2d6535e8378d.png)

**Comment by jyutzler** [comment]
:+1: Somewhere in the settings this was actively disabled. The setting (which is no longer visible) was in the core settings. I think what happened is that I disabled the extension because I wasn't using it and it was nagging me about something every time I started up. I guess a sideeffect of disabling the plugin is that it set the keybindings to disabled as well.

Thanks.
