### ISSUE TITLE
Feature: Add support for a REPL

### ISSUE THREAD

**Issue by Willyham** [lloiser/go-debug#88]
I believe that this is supported with the `print` command in Delve. Would it be possible to add a pane in the debugger column which gave us access to this? I generally find this one of the most important tools for debugging.

Happy to take a stab at implementing this (though I've not done any atom work before) if you can point me in the right direction.

**Comment by lloiser** [comment]
I've already started with this. Unfortunately I'm currently blocked by [a bug within a 3rd party lib](https://github.com/atom/etch/pull/51) that go-debug uses.

**Comment by lloiser** [comment]
see [`v1.3.1`](https://github.com/lloiser/go-debug/releases/tag/v1.3.1)
