### ISSUE TITLE
Plugin settings: default hidden

### ISSUE THREAD

**Issue by pkieltyka** [lloiser/go-debug#9]
Can there be a setting for this plugin to have it hidden by default? I can toggle it visible as I need?

**Comment by lloiser** [comment]
On the very first install it is visible (so the user sees it immediately, won't change that). After that it remembers whether it was visible or hidden.
Or is it another problem?

**Comment by pkieltyka** [comment]
I think thats a good way to do it too.. just remembering the previous setting. I’m finding its not remembering. It did at one point, but not anymore. I do typically have a bunch of windows open. But I did a full restart. Also using Atom 1.6.2


On April 7, 2016 at 9:22:56 AM, Lukas (notifications@github.com) wrote:

On the very first install it is visible (so the user sees it immediately, won't change that). After that it remembers whether it was visible or hidden.
Or is it another problem?

**Comment by lloiser** [comment]
Did some testing: it seems that each atom instance (opened from the same folder via command line) has it's storage to remember the settings for packages. So each atom instance has it's own value of "is go debug panel visible"... 
I could add a config whether the panel is visible from the beginning for new instances. Would this help?

**Comment by pkieltyka** [comment]
Perfect, that would help yes.


On April 7, 2016 at 1:41:45 PM, Lukas (notifications@github.com) wrote:

Did some testing: it seems that each atom instance (opened from the same folder via command line) has it's storage to remember the settings for packages. So each atom instance has it's own value of "is go debug panel visible"...
I could add a config whether the panel is visible from the beginning for new instances. Would this help?

**Comment by sadovnychyi** [comment]
It's pretty annoying that I can see that panel and commands in **non** go files.

You should display them only if grammar set to "Go".

```javascript
atom.commands.add("atom-workspace[data-grammar~=go]", { ...
```

This will require watching for grammar change events, but it will lead to much better expirience accross different languages.

Typing "debug" while looking on python file shouldn't give me suggestions about Go.

**Comment by lloiser** [comment]
I actually like it that it stays open for other languages, at least while debugging. After that it can be a bit annoying, true...
Maybe we can agree on a solution somewhere in the middle: add a config to hide the panel if the current file != go (also if currently debugging?)

> Typing "debug" while looking on python file shouldn't give me suggestions about Go.

Has nothing to do with go-debug, as it is the default behaviour of atom to autocomplete words based on all open tabs.

**Comment by sadovnychyi** [comment]
> Has nothing to do with go-debug, as it is the default behaviour of atom to autocomplete words based on all open tabs.

No, it's up to plugin to limit its commands to specific scopes. When I'm on Go syntax – I cannot see any autocomplete-python related commands. I can see them only while in *.py files.

**Comment by lloiser** [comment]
Oh! So you mean the commands to start debugging (like `F5`or `ctrl-F5`)? Yes these _could_ be restricted to go files only...

**Comment by sadovnychyi** [comment]
Yes, all this stuff should be available only if I'm in Go syntax. This will make command pallete more relevant and will allow for different language specific plugins to use same key bindings.

![image](https://cloud.githubusercontent.com/assets/193864/14382612/abb7c972-fdc1-11e5-9037-e970d15372ef.png)

**Comment by lloiser** [comment]
@sadovnychyi update to new version and check out the "Commands available only in go source" config

@pkieltyka update to new version and check out the "Panel initially visible" config
