### ISSUE TITLE
Failed to start delve with config "Test"

### ISSUE THREAD

**Issue by IamDH4** [lloiser/go-debug#95]
With a fresh install of Atom on Arch Linux. If I use the `Debug` config everything works as expected. But using the `Test` config it breaks:

```
Starting delve with config "Test"
Delve output: could not launch process: fork/exec ./debug.test: no such file or directory
delve closed with code 1
Failed to start delve with config "Test"
  Error: Error: Closed with code 1
```

No errors are thrown in the Atom developer tools console.

**Comment by lloiser** [comment]
`Test` means: _debug the tests in this package_. The error occurs if the package has no tests (to debug).

**Comment by IamDH4** [comment]
That makes sense, sorry for the post.
